### ISSUE TITLE
[Explore Contracts] Fix issue that prevents loading when bad address is used for base token

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/Dapp#68]
If a MARKET contract is deployed with a invalid address for the base token, it prevents contracts from loading in the explorer.
```

contract.js:435 Uncaught (in promise) Error: Cannot create instance of CollateralToken; no code at address 0x3333333333333333333333333333333333333333
    at Object.callback (contract.js:435)
    at method.js:142
    at requestmanager.js:89
    at XMLHttpRequest.request.onreadystatechange (httpprovider.js:128)
```

**Comment by maektwain** [comment]
In the case of contract address it throws error

``
web3.eth.call({to:"0x1411cb266fced1587b0aa29e9d5a9ef3db64a9c5", data:"0xc6888fa10000000000000000000000000000000000000000000000000000000000000003"})
Error: VM Exception while processing transaction: revert
``

And in the case when the address is not valid contract 

``js
web3.eth.call({to:"0x3333333333333333333333333333333333333333", data:"0xc6888fa100000000000000000000000000000000000000000000000000000000000003"})
Error: Attempting to run transaction which calls a contract function, but recipient address 0x3333333333333333333333333333333333333333 is not a contract address
    at Eth.send (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:145:1)
    at RequestManager.send (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:61:1)
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
``
